### ISSUE TITLE
Adding exclusions using flow-scanner.json

### ISSUE THREAD

**Issue by RaviVaranasi** [Lightning-Flow-Scanner/lightning-flow-scanner-core#226]
Is there an example that shows various values of `ResultName` in the [exception section](https://github.com/Lightning-Flow-Scanner/lightning-flow-scanner-core#exception-configuration)?

The use case/background is to modify the rules and add exceptions for legacy flows.

Below is an example:

```
{
  "exceptions": {
    "Flow_API_Name": {
      "UnusedVariable": [
        "2"
      ]
    }
  }
}
```

Why is `UnusedVariable` an array type?

Ravi

**Comment by junners** [comment]
Heya!
I don't have one documented in the tests on suppressing multiple results of the same rule. Closest one in [my tests is this](https://github.com/Lightning-Flow-Scanner/lightning-flow-scanner-core/blob/master/tests/Exceptions.test.ts#L791-L803)

Anyways, to explain.. 
```yaml

exceptions:
  Your_Flow_API_Name: # this is the holder for your flow definition that you will have suppression with.
    UnusedVariable: # this is the name of the rule that you want to suppress under the context of the flow
      - unusedVariable  # array of the `name` element of the xml group the violation belongs to
      - anotherUnusedVariable
      - someOtherUnusedVariable
    APIVersion: # this is another rule being suppressed in the same flow Your_Flow_API_Name
      - "55"  # element value, this needs to be a string
    UnconnectedElement:
      - unconnectedElement1 # array of the `name` element of the xml group the violation belongs to
      - unconnectedElement2
  
  AnotherFlowThatYouWantToSuppress:
    CyclomaticComplexity:
      - "25" # element value, this needs to be a string
```

Rule suppression accepts an array because rule violations can appear multiple times in the same flow.

The idea really is to get context on the suppression where it belongs to, so that it's managed from a flow level and not a rule level. 
If you want to exclude a specific rule or a rule doesn't apply to you. you can exclude them on the rule definitions.

```yaml
rules:
  APIVersion:
    severity: "error"

exceptions:
  YourFlowThatBypassesAPIVersion:
    APIVersion:
      - "52"
```

This example only runs APIVersion on all your flows, effectively excluding other rules in the [DefaultRuleStore](https://github.com/Lightning-Flow-Scanner/lightning-flow-scanner-core/blob/master/src/main/store/DefaultRuleStore.ts#L26-L47)

**Comment by RaviVaranasi** [comment]
Thanks for the quick response. What about `Missing Fault Path`, ` Recursive After Update` and `Trigger Order`

**Comment by junners** [comment]
You would use it the same way when you define an exception, all of them accepts an array of strings with the element name. Rule Names can be found on the rule definition that can be traced from the labels being displayed.
[Missing Fault Path](https://github.com/Lightning-Flow-Scanner/lightning-flow-scanner-core/blob/master/src/main/rules/MissingFaultPath.ts#L16)
[Recursive After Update](https://github.com/Lightning-Flow-Scanner/lightning-flow-scanner-core/blob/master/src/main/rules/RecursiveAfterUpdate.ts#L25)
[Trigger Order](https://github.com/Lightning-Flow-Scanner/lightning-flow-scanner-core/blob/master/src/main/rules/TriggerOrder.ts#L10)

```yaml
exceptions:
  flowDefinitionName:
    TriggerOrder:
      - triggerOrder # name of the tag since this is one per flow, it's just trigger order
    
    RecursiveAfterUpdate:
      - faultyAfterUpdateViolation # array of element `name` of the xml group the violation belongs to
    
    ..... etc
```
